services:
  app:
    build: ./app
    restart: on-failure:5
    environment:
      env_file: "aws.env"
    ports:
      - "8000"
    deploy:
      replicas: 3
    networks:
      - appnet


  nginx:
    build: ./nginx
    restart: on-failure:5
    ports:
      - "5000:80"
    networks:
      - appnet
    depends_on:
      - app

networks:
  appnet:
    driver: bridge
